Reporting task changes
shivam-r/TestProject pull request #116
Opened 2018-09-25 12:47 UTC by poojabh91

2018-09-25 15:33 UTC, ritwiksen requested changes
There are no. of changes that are needed mostly across the board. A major issue is that we are consuming EDM objects directly in the Controller layer.

2018-09-25 15:33 UTC, ritwiksen commented on DCode.Web/Security/AuthorizeReportingTask.cs
> +                {
Please remove braces as `if` is commented out.

2018-09-25 15:33 UTC, ritwiksen commented on DCode.Web/Security/AuthorizeReportingTask.cs
> +
Please remove all empty lines.

2018-09-25 15:33 UTC, ritwiksen commented on DCode.Web/Views/Reporting/SplitPerOffering.cshtml
> +
Please remove empty line breaks across the board.

2018-09-25 15:33 UTC, ritwiksen commented on DCode.Web/Views/Reporting/TopContributors.cshtml
> +<table class="table table-bordered table-responsive table-hover">
Can we componentize this table in a partial and use it in `TopContributors.cshtml` , `TopRequestors.cshtml` &  `SplitPerOffering.cshtml`.

2018-09-25 15:33 UTC, ritwiksen commented on DCode.Web/Views/ReportingBase/Base.cshtml
> +    @Scripts.Render("~/bundles/jquery")
`jquery` & `bootstrap` have already been loaded in `_layoutReporting.cshtml`. Is there a specific need to re-render them?

2018-09-25 15:33 UTC, ritwiksen commented on SearchApplication/Controllers/ReportingController.cs
> +            string conString = System.Configuration.ConfigurationManager.ConnectionStrings["DcodeConnectionString"].ToString();
A couple of observations here:

1) Can we use `using` blocks to auto-dispose of connection and command objects. 
2) Also, pulling up EDM objects directly into the controller layer isn't a good idea.
3) Would be best if we closed connections in a `finally` block.
4) Can store the connection string as a constant at the controller level.

2018-09-25 15:33 UTC, ritwiksen commented on SearchApplication/Controllers/TasksController.cs
> +            if (fm["ddl_Task_Type"].ToString() != "")
Please use `Convert.ToString()` in place of `.ToString()`.

2018-09-25 15:33 UTC, ritwiksen commented on SearchApplication/Global.asax.cs
> +using System.Linq;
Please remove unused `usings`.

2018-09-25 15:33 UTC, ritwiksen commented on SearchApplication/Views/Reporting/SplitPerOffering.cshtml
> +<table class="table table-bordered table-responsive table-hover">
Table can be reused across multiple views.

2018-09-25 15:33 UTC, ritwiksen commented on SearchApplication/Views/Security/AuthorizeReportingTask.cs
> +            if (internalUsers != null
Considering that this split was used at multiple places, could we think of creating an extension method for this.

2018-10-03 09:35 UTC, shivam-r approved these changes

2018-10-03 09:39 UTC, merged