Update for task with past due date to be removed from dashboard
shivam-r/TestProject pull request #65
Opened 2018-03-22 11:43 UTC by shivamssin

Updated changes for removal of task with past due date.

2018-03-22 11:48 UTC, ritwiksen requested changes

2018-03-22 11:48 UTC, ritwiksen commented on DCode.Data/RequestorRepository/RequestorRepository.cs
> +            return filteredRecords.ToList().Where(x => x.DUE_DATE >= DateTime.Now);
Please execute Where before the ToList().

2018-03-22 11:48 UTC, ritwiksen commented on DCode.Services/Contributor/ContributorService.cs
> +            foreach (var task in tasks)
Please ensure querying is done in the Repo layer.

2018-03-22 12:31 UTC, ritwiksen approved these changes
Looks good

2018-03-22 14:35 UTC, shivam-r requested changes
Need to check the status while doing the filter based on due date.

Requestor and contributor should be able to see the tasks past due date in their history tab if task is assigned or approved.

2018-07-17 09:42 UTC, ritwiksen commented
This PR is no longer relevant and can be closed.

2018-07-17 09:42 UTC, closed without merging