Added method for setting and inserting the offering code into database
shivam-r/TestProject pull request #94
Opened 2018-07-11 05:21 UTC by sirianishetty

2018-07-11 05:31 UTC, ritwiksen requested changes
As discussed offerings and portfolio tables are readonly. Please make the modifications as necessary.

2018-07-11 05:36 UTC, shivam-r requested changes

2018-07-11 05:36 UTC, shivam-r commented on DCode.Services/Common/CommonService.cs
> +        {
Can you please optimise this code. Don't use ToList() with each reference to offerings. Please set it in local variable once before going into loop and use that temp variable.

2018-07-11 05:36 UTC, shivam-r commented on DCode.Services/Common/CommonService.cs
> +        public void SetOfferingCodeAndInsertIntoDb(IEnumerable<offering> offerings)
Why do we need this method? Offerings will already have a predefined code.

2018-07-20 04:09 UTC, closed without merging

2018-07-20 04:10 UTC, ritwiksen commented
Closing this PR as the functionality is already in place.